<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>enterprise_order_management</RootNamespace>
    <UserSecretsId>36a92ec6-175c-47b2-86fc-c09181f4d8ce</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Applications\**" />
    <Content Remove="Applications\**" />
    <EmbeddedResource Remove="Applications\**" />
    <None Remove="Applications\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\" />
    <Folder Include="Infrasctructure\Repositories\" />
  </ItemGroup>

</Project>
